livereload_script: http://vagrant.local:35730/livereload.js

superlearn_url: "https://superlearn.localhost"

collections:
  postgres:
    output: true
    title: "Postgres"
  erlang:
    output: true
    title: "Erlang"
  clojure:
    output: true
    title: "Clojure"
  spanish:
    output: true
    title: "Spanish"
  korean:
    output: true
    title: "Korean"


